spring:
  application:
    name: Hana1Pick

  datasource:
    url: ENC(1bABXwaT1V38CgkPMc2mUm3NbEhkEzpZD8RDXc97VJVO8+ht6pXIvox3wG2QNqheBdwlk328vhMl7NQBUFjV6Zz7uuLzKZi+c55w40oUdJJ860FZ/Jkr05UGnsoe2iJA)
    username: ENC(hcNtwlmLW45yLgLo1SCenQ==)
    password: ENC(sDTTfhyMJjrINkuZI2c+i53Mud2AEKEQ)
    hikari:
      max-lifetime: 177000

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          default_batch_fetch_size: 1000