server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: Hana1Pick
  datasource:
    url: ENC(1bABXwaT1V38CgkPMc2mUm3NbEhkEzpZD8RDXc97VJVO8+ht6pXIvox3wG2QNqheBdwlk328vhMl7NQBUFjV6Zz7uuLzKZi+c55w40oUdJJ860FZ/Jkr05UGnsoe2iJA)
    username: ENC(hcNtwlmLW45yLgLo1SCenQ==)
    password: ENC(sDTTfhyMJjrINkuZI2c+i53Mud2AEKEQ)
    hikari:
      max-lifetime: 177000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(sKNJHs6GxopYsPXKdf7UCg==)

  springdoc:
    swagger-ui:
      tags-sorter: method
      display-request-duration: true
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    cache:
      disabled: true
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-81

app:
  kakao:
    rest_api_key: ENC(2dRfMOBeXknUrSUVvEcI8IkW+4/p1b62TztLehKIZ8BEdqc/oaA067MLJB1uR3vh)
    login-redirect: /api/user/oauth/kakao
    logout-redirect: /api/user/logout/kakao
    url:
      login: https://kauth.kakao.com/oauth/authorize
      logout: https://kauth.kakao.com/oauth/logout
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink

jasypt:
  encryptor:
    password: gkskdnjsvlr2@
